#! /bin/sh

BASE=$HOME

PORTALS='
XXX
'

for portal in $PORTALS; do
    cd $BASE/lmconfig/$portal || exit 1
    $BASE/lmapi-scripts/lm-get-configs --company $portal "$@"
    for repo in *; do
	if [ "$repo" = "*" ]; then
	    (cd $repo || exit 1;
	     git add *;
	     git diff --exit-code --staged > /dev/null; 
	     if [ $? -ne 0 ]; then
		 git commit -q -a -m "lm-get-configs:$repo" >/dev/null
		 git push -q >/dev/null
	     fi
	    )
	fi
    done
done
